runtime: nodejs10
service: lorem

env_variables:
    REACT_APP_API_URL: https://skola-core.et.r.appspot.com/api/

automatic_scaling:
    max_instances: 1

handlers:
    - url: /
      static_files: build/index.html
      upload: build/index.html
    - url: /(.*)$
      static_files: build/\1
      upload: build/(.*)